version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
      - ./.docker/database:/docker-entrypoint-initdb.d
    ports:
      - ${DOCKER_DATABASE_PORT:-3306}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - database
      - composer
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    ports:
      - ${DOCKER_BACKEND_PORT:-80}:80
    volumes:
      - ./backend:/var/www/html
      - ./.docker/apache.conf:/etc/apache2/sites-available/000-default.conf

  composer:
    container_name: composer
    image: composer:2
    command: 'install --optimize-autoloader --ignore-platform-reqs'
    volumes:
      - ./:/app
      - composer-cache:/tmp

  frontend:
    container_name: frontend
    image: node:16
    command: bash -c "cd app && npm start"
    ports:
      - ${DOCKER_FRONTEND_PORT:-3000}:3000
    volumes:
      - ./frontend:/app

volumes:
  mysql:
  composer-cache: